name: CI Jest-SuperTest

on: [push, pull_request]

jobs:
  test-newman-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: Jest-SuperTest

    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Instalar Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '20'

       - name: Instalar dependencias
         run: npm install

       - name: Correr tests de Personas
         run: npm test -- test/api.personas.spec.js
          
          
          